# Generated by Django 6.1.1 on 2026-09-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_supplier",
            field=models.BooleanField(default=False, verbose_name="Поставщик"),
        ),
    ]
