# Generated by Django 6.1.1 on 2026-09-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
